repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-xml
      - id: check-yaml
      - id: check-added-large-files
      - id: check-byte-order-marker
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: detect-private-key
      - id: check-json
      - id: check-symlinks
      - id: pretty-format-json
        args: [--autofix, --no-sort-keys]
  - repo: git://github.com/antonbabenko/pre-commit-terraform
    rev: v1.35.0
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
      - id: terraform_docs_without_aggregate_type_defaults
      - id: terraform_tflint
