name: security-check

on:
  pull_request:
    branches:
      - master
  push:
    branches: [master]

jobs:
  security-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Perform ShiftLeft Scan
      uses: ShiftLeftSecurity/scan-action@master
      with:
        output: reports
        type: credscan,python,terraform,yaml,bash,depscan
